CREATE DATABASE BOOKSTORE
GO 
USE BOOKSTORE
GO
CREATE TABLE PUBLISHER(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(255),
)
CREATE TABLE BOOKS(
	ID INT IDENTITY PRIMARY KEY,
	TITLE NVARCHAR(255),
	EXCERPT NVARCHAR(255),
	[DESCRIPTION] NVARCHAR(255),
	PUBLISH_DATE DATE,
	PRICE INT,
	BOOK_URL NVARCHAR(255),
	PUBLISHER_ID INT FOREIGN KEY REFERENCES PUBLISHER(ID) ON DELETE CASCADE
)
CREATE TABLE BOOK_IMAGE(
	ID INT IDENTITY PRIMARY KEY,
	IMAGE1 NVARCHAR(255),
	IMAGE2 NVARCHAR(255),
	IMAGE3 NVARCHAR(255),
	IMAGE4 NVARCHAR(255),
	BOOK_ID INT FOREIGN KEY REFERENCES BOOKS(ID) ON DELETE CASCADE
)
CREATE TABLE AUTHOR(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(255)
)
CREATE TABLE BOOK_AUTHOR(
	ID INT IDENTITY PRIMARY KEY,
	BOOK_ID INT FOREIGN KEY REFERENCES BOOKS(ID) ON DELETE CASCADE,
	AUTHOR_ID INT FOREIGN KEY REFERENCES AUTHOR(ID) ON DELETE CASCADE
)
CREATE TABLE CUSTOMERS(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(255),
	USERNAME NVARCHAR(255),
	[PASSWORD] NVARCHAR(255),
	GENDER BIT,
	[ADDRESS] NVARCHAR(255),
	EMAIL NVARCHAR(255),
	PHONE NVARCHAR(255),
	[ROLE] INT DEFAULT 0
)
CREATE TABLE WHISHLIST(
	ID INT IDENTITY PRIMARY KEY,
	BOOK_ID INT FOREIGN KEY REFERENCES BOOKS(ID) ON DELETE CASCADE,
	[CUSTOMER_ID] INT FOREIGN KEY REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
)
CREATE TABLE GENRE(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(255)
)
CREATE TABLE BOOK_GENRE(
	ID INT IDENTITY PRIMARY KEY,
	BOOK_ID INT FOREIGN KEY REFERENCES BOOKS(ID) ON DELETE CASCADE,
	GENRE_ID INT FOREIGN KEY REFERENCES GENRE(ID) ON DELETE CASCADE,
)
CREATE TABLE [ORDER](
	ID INT IDENTITY PRIMARY KEY,
	[ADDRESS] NVARCHAR(255),
	EMAIL NVARCHAR(255),
	PHONE NVARCHAR(255),
	TOTALAMOUNT INT,
	CREATED_DATE DATE,
	[STATUS] BIT,
	PAYMENTMETHOD INT,
	[CUSTOMER_ID] INT FOREIGN KEY REFERENCES CUSTOMERS(ID) 
)
CREATE TABLE ORDERDETAIL(
	ID INT IDENTITY PRIMARY KEY,
	AMOUNT INT,
	PRICE INT,
	QUANTITY INT,
	NOTE NVARCHAR(255),
	ORDER_ID INT FOREIGN KEY REFERENCES [ORDER](ID) ON DELETE CASCADE,
	BOOK_ID INT FOREIGN KEY REFERENCES BOOKS(ID)
)
CREATE TABLE POST(
	ID INT IDENTITY PRIMARY KEY,
	TITLE NVARCHAR(255),
	EXCERPT NVARCHAR(255),
	CONTENT NVARCHAR(MAX),
	[STATUS] INT,
	CREATED DATE,
	POSTURL NVARCHAR(255),
	[CUSTOMER_ID] INT FOREIGN KEY REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
)
CREATE TABLE COMMENT(
	ID INT IDENTITY PRIMARY KEY,
	[STATUS] INT,
	CREATED DATE,
	EMAIL NVARCHAR(255),
	NAME NVARCHAR(255),
	POST_ID INT FOREIGN KEY REFERENCES POST(ID) ON DELETE CASCADE,
) 
GO